### ISSUE TITLE
TDAP053- Create API field to store task date

### ISSUE THREAD

**Issue by amit-ib** [amit-ib/Todo-v2#42]
Please create a new field "todoDate" with datatype "Date", thanks

**Comment by akash-dhande-ib** [comment]
What do you think about adding
`dueDate` and `completedDate`

**Comment by amit-ib** [comment]
I agree both fields are needed, kindly add them, thanks

**Comment by akash-dhande-ib** [comment]
Hi @amit-ib 

I have added the fields.
![image](https://user-images.githubusercontent.com/96531168/192812061-b2951235-91b8-4c06-a0e0-042e4f6d8752.png)

Please let me know if anything else required.

Thanks
Akash

**Comment by amit-ib** [comment]
all good, thanks
